[package]
name = "mc-user-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.0.0-pre.15"
same-file = "1.0.6"
anyhow = "1.0.58"
tokio = { version = "1.19.2", features = ["full"] }